a = input("enter your name\n")
b = int(input("enter your usn\n"))
c = int(input("enter your phone num\n"))
d = int(input("enter your age\n"))

print("-----student details-----")
print("name:",a)
print("usn:",b)
print("phone num:",c)
print("age:",d)